### ISSUE TITLE
Boys

### ISSUE THREAD

**Issue by Nekuskus** [cat-milk/Anime-Girls-Holding-Programming-Books#120]
Has the other repo mentioned in #73 ever been created? I would like to see something like it especially now that Oreki was mentioned

**Comment by Asday** [comment]
Not that I know of.

This is your perfect opportunity to be the change you want to see in the world.

**Comment by TheHaff** [comment]
@Nekuskus obviously create a competing repo with anime bois

**Comment by jxu** [comment]
![image](https://user-images.githubusercontent.com/7989982/86331820-99461c80-bc17-11ea-8696-1c2823ba75a3.png)

does this count

**Comment by Asday** [comment]
@jxu that's not really related to this issue.  You'd be best opening a separate one if you _really_ want the answer.

**Comment by CinnamonJui** [comment]
Here you go [westofer/Anime-Boys-Holding-Programming-Books](https://github.com/westofer/Anime-Boys-Holding-Programming-Books)

**Comment by devomaa** [comment]
that got deleted

**Comment by flyingcakes85** [comment]
@devomaa 
I created one, but its empty right now. Will need contributors since I ain't got much knowledge of photo editing.
https://github.com/flyingcakes85/Anime-Boys-Holding-Programming-Books

**Comment by Asday** [comment]
Motion to close.

**Comment by Kholodets** [comment]
best of luck with anime boys
