### ISSUE TITLE
Add a Chinese Rust book - 《The Tao of Rust》

### ISSUE THREAD

**Issue by ZhangHanDong** [cat-milk/Anime-Girls-Holding-Programming-Books#167]
![image](https://user-images.githubusercontent.com/27893/105108609-90eef980-5af5-11eb-9615-b8d443247f11.png)

**Comment by rbbl-dev** [comment]
open a pr i guess

**Comment by cat-milk** [comment]
Good image but this should be a PR

**Comment by ZhangHanDong** [comment]
@cat-milk  ok
