### ISSUE TITLE
Permission to use images anywhere.

### ISSUE THREAD

**Issue by g-n-x** [cat-milk/Anime-Girls-Holding-Programming-Books#177]
I see this repo don't have any licensing at all. Would it be okay to use the images anywhere I want?

**Comment by HawaiinPizza** [comment]
Yes

**Comment by raynet** [comment]
Quick look on the images shows they are not original art, thus there might be copyright issues if you use them.

**Comment by Asday** [comment]
I do like that some rando came in and gave permission though.  That sort of wild misinformation pleases me.

**Comment by damaera** [comment]
This is not legal, obviously.

Copyrighted images, are not a good idea to use unless you have written/email permission from the Owner of the property.
So don't use this image on your **Commercial** project!

**Comment by Kholodets** [comment]
The images in this repo are all derivative works of likely copyrighted works of various artists. This repo is for fun and should be used as such, do not use the images in any commercial or high profile cases without contacting the original artist and perhaps the person who uploaded it if they made the edit.
