### ISSUE TITLE
Need Anime Boys Holding Programming Books Too

### ISSUE THREAD

**Issue by PrajjwalDatir** [cat-milk/Anime-Girls-Holding-Programming-Books#224]
Title explains it.

**Comment by kotx** [comment]
You're in luck: https://github.com/flyingcakes85/Anime-Boys-Holding-Programming-Books

**Comment by flyingcakes85** [comment]
Yeah I need contributors...

I'll admit - I watch mostly those anime which are dominated by girls, so I don't know many anime boys....

If someone just shares anime boys pics, I'll do the editing part.

**Comment by Asday** [comment]
Go watch Fate.  Plenty of good boys in that.

**Comment by PrajjwalDatir** [comment]
@flyingcakes85 ok I will send If I find any...

**Comment by Asday** [comment]
Motion to close.

**Comment by PrajjwalDatir** [comment]
Well, closing it D:
