### ISSUE TITLE
Game Engine dir

### ISSUE THREAD

**Issue by annaDostoevskaya** [cat-milk/Anime-Girls-Holding-Programming-Books#248]
make dir with game engine books
[example](https://sun9-86.userapi.com/impg/qjYHTPcZb-wpSkrDzxKbvwAusBoPJveNeDsQpA/ZsWW_pZCuHQ.jpg?size=909x1080&quality=96&sign=aa8a528f49e952937aa2f00cfb8c082b&type=album)

**Comment by annaDostoevskaya** [comment]
How i can bind this issue with pull request about Game Engine Dir?..

**Comment by kotx** [comment]
Maybe put something like "Closes #248" in the description or a commit message
