### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by llucere** [cat-milk/Anime-Girls-Holding-Programming-Books#279]

**Comment by Asday** [comment]
:-1:

**Comment by Twikzer** [comment]
what is this?

**Comment by Asday** [comment]
Some nerd mad at girls.

**Comment by llucere** [comment]
> Some nerd mad at girls.

i love anime girls but this repo is just a **bruh** imo

**Comment by flyingcakes85** [comment]
> this repo is just a **bruh** imo

In that case, you can set your watch status to "Ignore". That way, GitHub shall never send you any notifications about this :)

![image](https://user-images.githubusercontent.com/48585950/146953178-f74ed517-f15e-4ad1-8595-de51cd478891.png)

**Comment by Asday** [comment]
@llucere then fuck off.
