### ISSUE TITLE
ADA should have a military themed alternative

### ISSUE THREAD

**Issue by joaomcarlos** [cat-milk/Anime-Girls-Holding-Programming-Books#290]
Missed opportunity to add a military themed alternative to ADA.

Unfortunately I cant help much as I am not that into anime, but given the ADA programming language main uses, I think those would fit perfectly!

**Comment by Asday** [comment]
Vote to close.

Be the change you want to see, or don't complain.

**Comment by cat-milk** [comment]
If what your asking for is military themed anime girls with ADA books you could create those images yourself and open a PR which I'd be happy to merge.
If youre asking about non-anime military stuff then that really doesn't fit the theme of this repo

**Comment by cat-milk** [comment]
Either way I'm closing this issue

**Comment by joaomcarlos** [comment]
Given that ADA is heavily used in military applications. Probably its biggest use. I suggested the theme.

If you are not open to suggestions, hey, thats ok too. Have fun :D
