### ISSUE TITLE
Anime girls holding O'Rly funny mocks by Practical Dev

### ISSUE THREAD

**Issue by ldeluigi** [cat-milk/Anime-Girls-Holding-Programming-Books#302]
See this sticker pack on telegram:
https://t.me/addstickers/ThePracticalDevOrlyUnofficial
And this repo with some high res images:
https://github.com/thepracticaldev/orly-full-res

**Comment by cat-milk** [comment]
Hmmm adding some of these would definitely be funny but I think they would have to go into their own directory so we don't have a bunch of joke books next to real ones.

Something like `Orly_Mocks/`

**Comment by Kholodets** [comment]
Closing, anyone is free to add new categories via a PR if they have images they would like to add.
