### ISSUE TITLE
Felix Argyle isn't a girl

### ISSUE THREAD

**Issue by aetinx** [cat-milk/Anime-Girls-Holding-Programming-Books#304]
Not a girl: https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/blob/master/Javascript/Felix_Argyle_Scared_By_JavaScript_The_Good_Parts.png

(You should make anime boys and femboys holding programming books!)

**Comment by kotx** [comment]
https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/issues/258#issuecomment-954228380

**Comment by flyingcakes85** [comment]
https://github.com/flyingcakes85/Anime-Boys-Holding-Programming-Books/

Emptyish repo, but could get some love

**Comment by cat-milk** [comment]
Felix is female enough

From the ReadMe:

> All characters added pretty much always must be female presenting, meaning that they are either canonically female or at least look and act like they're girls.
