### ISSUE TITLE
what means “NO CRYPTO GO AWAY”

### ISSUE THREAD

**Issue by bluedoom** [cat-milk/Anime-Girls-Holding-Programming-Books#333]
I google it and didn't get properly explanation.

**Comment by Asday** [comment]
Please apply some critical thinking.

**Comment by cat-milk** [comment]
Im afraid id get banned if I told you to go away with the particular phrasing i want to use

**Comment by Kholodets** [comment]
What I think she means to say is that we are not inclined to allow any content directly relating to cryptocurrency or closely related technologies on this repo, sorry for any confusion @bluedoom

**Comment by bluedoom** [comment]
> What I think she means to say is that we are not inclined to allow any content directly relating to cryptocurrency or closely related technologies on this repo, sorry for any confusion @bluedoom

Thanks，I get it!
