### ISSUE TITLE
Yumeko Jabami with Rust

### ISSUE THREAD

**Issue by uwussimo** [cat-milk/Anime-Girls-Holding-Programming-Books#336]
Please, add [Yumeko Jabami](https://kakegurui.fandom.com/wiki/Yumeko_Jabami) with Rust please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please!

**Comment by cat-milk** [comment]
ill merge it when i get to it stop being weird
