### ISSUE TITLE
photoshoped

### ISSUE THREAD

**Issue by crzypatchwork** [cat-milk/Anime-Girls-Holding-Programming-Books#375]
this one is so good but it shows it's bad photoshop https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/blob/master/C/Lain_studying.png
![image](https://user-images.githubusercontent.com/24375224/158013922-2c96a7e2-97f7-45d7-b375-ba14a35430f6.png)

**Comment by lewyche** [comment]
Plus she's not even holding the book

**Comment by Asday** [comment]
So submit a PR.  :-1:

**Comment by crzypatchwork** [comment]
> So submit a PR. 👎

ty for the suggestion
