### ISSUE TITLE
Minor naming issue

### ISSUE THREAD

**Issue by mys31f** [cat-milk/Anime-Girls-Holding-Programming-Books#383]
[Picture](https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/blob/master/Design%20Patterns/Girl_From_Random_Art_Holds_THe_Art_Of_Computer_Programming.png)
The girl in here is Rina Tennoji from Love Live, more specifically in Nijigasaki.

**Comment by asheeeshh** [comment]
opening a pr to rename it as no one else seems to have done it yet.

**Comment by Kholodets** [comment]
closing, that file is a duplicate of this anyways https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/blob/master/Algorithms/Rina_Tennoji_Holds_Russian_The_Art_Of_Computer_Programming.png
