### ISSUE TITLE
Track down pic of Elma reading OO book from Kobayashi's Dragon maid

### ISSUE THREAD

**Issue by MoltenEQ** [cat-milk/Anime-Girls-Holding-Programming-Books#444]
I have found the following pick, should fit this repo. Can anyone get a good quality pic of it?
[Source:](https://loginportal.funnyjunk.com/pictures/Elma+is+a+hard+worker+trigger+mentionlist+lewds4dheart_18a612_6225585.jpg)
![image](https://user-images.githubusercontent.com/78501629/166820796-3a34b1ef-8f75-4c8c-b19a-a835003b6a14.png)

**Comment by hdk5** [comment]
#404
