### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Oreoezi** [cat-milk/Anime-Girls-Holding-Programming-Books#457]

**Comment by Oreoezi** [comment]
https://github.com/Asday/kanojo

I think I am

**Comment by Asday** [comment]
Being like "haha you like anime" isn't a great own when we're both on an anime-related repository.  I'll give you another try seeing as I'm feeling generous.

**Comment by CookieRabbit** [comment]
you came all the way here to judge? you searched *anime* just to laugh at it?

**Comment by SoftwareGuy** [comment]
Pretty sure this was bait.

**Comment by Asday** [comment]
Why would I miss an opportunity to beat my chest about what I love tho?
