### ISSUE TITLE
Image at wrong place: Javascript/Zero_Two_Holding_Nodejs_8_the_Right_Way

### ISSUE THREAD

**Issue by pog5** [cat-milk/Anime-Girls-Holding-Programming-Books#461]
It should be moved to nodejs/

**Comment by wellsilver** [comment]
JavaScript is nodejs...

**Comment by Kholodets** [comment]
separation of languages, frameworks, and runtimes is somewhat arbitrary at the moment, oh, there is a nodejs folder, but its pretty small, if anything I would be inclined to move those to the JS folder, however, it's not that big a deal, if you feel something is substantially misclassified though, you're free to make the change and submit it via a PR
