### ISSUE TITLE
Update Contributing Guidelines

### ISSUE THREAD

**Issue by Allyson04** [cat-milk/Anime-Girls-Holding-Programming-Books#490]
The current guidelines explained on "README.md" or "CONTRIBUTING.md" needs a bit of update, either to be more concise or clearer. Some notes:

* Each file above have their own rules, they need to have be the same (The "no Crypto" rule is just on README for example);
* "No Crypto" rule is not clear enough for some people (like issue https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/issues/333);
* Change "Nudity" to "NSFW" (All nudity is NSFW, but not all NSFW is nudity, with this difference, it's safer to allow only SFW content);
* Update current name convention. The current one is just "File_Names_Are_Cool.png", but the true convention is "Character_Name_ Book_Name.png", this can be seen by looking some merges and fixings made on filenames on master branch. There's currently another Issue about changing this convention (see https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/issues/285), but for now, the "Character_Name_ Book_Name.png" should be the one used.

**Comment by Kholodets** [comment]
solved by #491
