### ISSUE TITLE
WEB

### ISSUE THREAD

**Issue by ShADAMoV** [cat-milk/Anime-Girls-Holding-Programming-Books#512]
I am frontend-developer and anime-watcher (master lvl). I was so sad, because can't find learning material in web [9_9]

**Comment by Asday** [comment]
Then open a PR.

**Comment by weebcyberpunk** [comment]
be the change you wanna see ;)

**Comment by Asday** [comment]
Can't believe this legend stole my line.

**Comment by weebcyberpunk** [comment]
lol 😂
