### ISSUE TITLE
License file missing, images being used for commercial purposes.

### ISSUE THREAD

**Issue by jannes-io** [cat-milk/Anime-Girls-Holding-Programming-Books#513]
Now obviously licensing is a bit of an issue, considering most images here are photoshops which I doubt are transformative enough to fall under fair use.

However, recently I stumbled upon this: https://www.redbubble.com/i/iphone-case/Cute-Anime-Girl-Haskell-Programming-Book-by-mythical-design/99313308.E69SZ

Which is technically my art, I made the original menhera-chan holding the LYHGG photoshop. And a lot more from here are on that site. Clearly someone is trying to make a quick buck from the work everyone here did.

Just felt like some awareness here was required and, AFAIK, people cannot use code or resources from repositories that do not have a license.

[GitHub help page](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license):
> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by jannes-io** [comment]
Here's some more:
https://www.redbubble.com/i/iphone-case/Cute-Anime-Girl-Haskell-Programming-Book-by-mythical-design/99313308.E69SZ
https://www.redbubble.com/i/iphone-case/Cute-Anime-Girl-Modern-Vim-Book-by-mythical-design/99309939.E69SZ
https://www.redbubble.com/i/iphone-case/Cute-Anime-Girl-Programming-in-D-Book-by-mythical-design/99024654.E69SZ
https://www.redbubble.com/i/iphone-case/Cute-Anime-Girl-Go-Programming-Book-by-mythical-design/99312316.E69SZ
https://www.redbubble.com/i/iphone-case/Cute-Anime-Girl-Learn-Java-12-Programming-Book-by-mythical-design/99021539.E69SZ
https://www.redbubble.com/i/iphone-case/Cute-Anime-Girl-Javascript-Good-Parts-Book-by-mythical-design/99315390.E69SZ
https://www.redbubble.com/i/iphone-case/Cute-Anime-Girl-Rust-Programming-Book-by-mythical-design/101711988.E69SZ
https://www.redbubble.com/i/iphone-case/Cute-Anime-Girl-Deno-Nodejs-Book-by-mythical-design/99321806.E69SZ

@cat-milk  you could submit a takedown request:
https://help.redbubble.com/hc/en-us/requests/new?ticket_form_id=360000954531

Or add a license file that allows commercial use I suppose?

**Comment by Asday** [comment]
You drew the original?  Or you photoshopped it to hold a book?  If it's the former you can go submit a DMCA to redbubble yourself, (and this repo if you're feeling particularly vindictive).  If it's the latter, like you said, probably wouldn't count as transformative, and you have absolutely no right to claim ownership of it to have an opinion on it being sold, that's for the original artist to do.  In that case you can go snitch to them.

On a lighter note - literally who cares lmao it's fuckin' anime meme pictures used on imageboards, we already have license request issues and MRs (#65 #64) in which I've pontificated endlessly, and which were summarily closed.

**Comment by jannes-io** [comment]
I think you misunderstood the issue, but I understand where you’re coming from. I never claimed I drew the original, simply that I made the photoshopped version, which is how I found out that it came from here.

Once you submit something to a repository you hand over ownership, in this case to the repository owner, and since the repository is unlicensed, nobody has the rights to use anything in this repository as it falls under copyright.

If people knew that some guy was going to use it for blatant cash grabbing before submitting their photoshops, maybe it’d be a different story. These photoshops still take some time and there’s no credit or even a mention of where the images came from.

Selling images from here is just disrespectful and straight up against the law. So if a permissive license is added it would make the contributors here aware of what their photoshops are being used for, whereas now they think it won’t be used for commercial goals. And as long as no license is added, these blatant ripoffs should be reported. Only the repository owner (@cat-milk ) can do this as they own the copyright for anything in this repository.

**Comment by Asday** [comment]
So @ the guy who submitted the file.  You're overthinking this, relax.

**Comment by garciaErick** [comment]
So based on what people have been commenting on this thread I have formed this conclusion: 

Its ok for me to make a script to scrub the images on this repo to put up a dynamic store using these images and sell them on boiler plate material :D

**Comment by Asday** [comment]
You might have reading comprehension issues then, or perhaps mental deficiencies.  The maintainers of the repo make no guarantee about anything.  Lifting the images for any reason including commercial is probably outside the bounds of any law.  To quote a great man, this repo's maintainers are essentially saying "what am I, the copyright police?"

**Comment by garciaErick** [comment]
whooaaaaaaah haha a big escalation on your part, and also insulting... to quote a wise person without reading deficiencies:
> literally who cares lmao it's fuckin' anime meme pictures used on imageboards

Sorry if I got on your nerves just a joke, but if I got you mad then maybe @jannes-io had an actual point with constructive criticism. Somebody is making money out of this cool project that a lot of people like. 
Key points to mention:

* What needs to be done (ideally)?
* What can be done in this scenario? (Realistically)
* What cannot be done, and what is currently being done. (e.g, bullshit we just have to just "compromise" on)
 
I don't think nobody is trashing the repo's maintainers and I think it is a valid concern and discussion. "Whatever just @theGuy", "we are not copyright police", "you are mentally deficient and have comprehension issues", is not at all what the open source community or the Anime girls holding programming books community is about imo.

**Comment by garciaErick** [comment]
I know its hard replying to randos online and not getting mad haha but obviously this is going to get asked over and over as more people contribute and this gets known. The ideal case would be people reading the previous opened issues. If you actually hate responding this over and over, we could just make some PR summarizing these discussions on why we don't/can't have a license.

**Comment by Asday** [comment]
The internet is not serious business.  I know you've been tricked by the domain name, but you forgot to realise culture is repo-wise not site-wise.  Jog on.

**Comment by garciaErick** [comment]
U got mad hahaha you definitely are taking it serious lmao. Bye ~

**Comment by Asday** [comment]
For sure dude, pointing out your room temperature IQ is definitely me simmering.  I'm about to pop.

**Comment by Asday** [comment]
:chart_with_upwards_trend:

**Comment by jannes-io** [comment]
Woah. If I'd have known this issue would blow up like this, I'd have never made it. **Regardless of the copyright involved of the original images** (there could be a debate whether or not this repo falls under fair use, probably not though), it's GitHub's license that protects any repository that doesn't have a license file. The original artists can dispute a copyright claim or DMCA takedown for images inside of this repo, but for all intents and purposes, all images inside this repository are strictly copyright protected and can not be used for commercial use. If the original artist doesn't agree with that, they need to dispute this repository.

It's just not right that people are scraping these images with 0 effort and pushing them onto some eye brow raising merch store to make a quick buck.

Anyway, issue is closed, I thank everyone who seriously participated in the conversation (@EvelynSubarrow , @garciaErick) and we'll simply move on. Seems like @Asday hostility reflects that they've got some skin in the game, perhaps even using stuff in this cool project for their own gain. Although looking at their repositories, I don't think they'd be capable of that.

That said, I'm unsubscribing from the issue. What a clown fest 🤡...

**Comment by Asday** [comment]
> Seems like @Asday hostility reflects that they've got some skin in the game, perhaps even using stuff in this cool project for their own gain

You're absolutely correct @jannes-io, my ultimate goal is the eradication of human stupidity, and a few of the people in this thread have shown me how much work is left to do.

**Comment by garciaErick** [comment]
[edgelord_69_420](https://github.com/Asday)
