### ISSUE TITLE
Anime-Femboys-Holding-Programming-Books?

### ISSUE THREAD

**Issue by ItsBranK** [cat-milk/Anime-Girls-Holding-Programming-Books#590]
Petition for astolfo and felix to be moved to a separate femboy related programming books site

**Comment by ger3tto** [comment]
no.

**Comment by gboncoffee** [comment]
no.

**Comment by kiraio-moe** [comment]
Nope.

**Comment by BrightOS** [comment]
yes.

**Comment by AntonCkya** [comment]
> yes.

r u donkey?

**Comment by BrightOS** [comment]
> > yes.
> 
> r u donkey?

no u

**Comment by all123all** [comment]
Why don't you create a new repository? I mean, i don't really like femboys and traps, but if you like it so much then you should create a new one. Just saying.

**Comment by ItsBranK** [comment]
> Why don't you create a new repository? I mean, i don't really like femboys and traps, but if you like it so much then you should create a new one. Just saying.

Just a suggestion, since they are femboys/traps in this current repo; I thought I'd be better to separate or categorize them since its called anime "girls" yet the first two images when you go to the site are men.

**Comment by all123all** [comment]
> > Why don't you create a new repository? I mean, i don't really like femboys and traps, but if you like it so much then you should create a new one. Just saying.
> 
> Just a suggestion, since they are femboys/traps in this current repo; I thought I'd be better to separate or categorize them since its called anime "girls" yet the first two images when you go to the site are men.

I agree with, that's why i said you should create a new repo. I'm not fond of femboys/traps ideology, but i think i could kinda help

**Comment by empty-quiver** [comment]
If you want to do this you can just fork it yourself.
